### ISSUE TITLE
Add navigation header

### ISSUE THREAD

**Issue by joseph-behrens** [nplutt/vaccine-availability-notifications#1]
Add navigation header to the website so that users can navigate from the home page to the preferences page and vice versa.

@nplutt I'm willing to help out. This was the first on your list, but let me know if I should grab something else.

**Comment by nplutt** [comment]
Sounds good to me! I'm using the react bootstrap library, there's a component in there that you can probably use.

The document is pretty limited, this should get the UI up and running though:
```bash
cd ui
npm install
npm run start
```

**Comment by joseph-behrens** [comment]
I was afraid you were going to say that :)
I've tried that a couple times last night and just now but I get an error about missing `../lib/api` from `src/pages`. I did some digging but couldn't figure out if there was a missing package or build step.

_(I'm just commenting out the calls to api for now to be able to run it since I don't need to test submitting anything)_
