### ISSUE TITLE
Add ability to send an email to manage your preferences from the website

### ISSUE THREAD

**Issue by joseph-behrens** [nplutt/vaccine-availability-notifications#3]
Ability to send an email to manage your preferences from the website

@nplutt It looks like you're using SES? Is that the tool you were planning to use for the incoming message and then I could work on a Lambda to process it for this task? Is there a dev environment or steps I should know about to run the API locally beyond `chalice local`?

**Comment by nplutt** [comment]
Unfortunately I don't have a great way to run the API locally outside of my account. I'll look at creating a test harness around the API or migrating the Terraform into this repo to make it easier for other people to work on.

It could probably broken down into a two smaller pieces of work.
1. Create an endpoint, maybe something like a `POST` to `/user/manage_preferences`
    * Accepts a JSON body with an `email` field
    * Look up the user by `email` using the [fetch_user](https://github.com/nplutt/vaccine-availability-notifications/blob/89af257e46244d6c48e29b0749c8cf972210ff08/api/chalicelib/services/user_service.py#L58) function
    * If the user exists send them an email using the [send_emails_to_users](https://github.com/nplutt/vaccine-availability-notifications/blob/89af257e46244d6c48e29b0749c8cf972210ff08/api/chalicelib/services/email_service.py#L44) function
    * Create a new [EmailTemplate](https://github.com/nplutt/vaccine-availability-notifications/blob/89af257e46244d6c48e29b0749c8cf972210ff08/api/chalicelib/services/email_service.py#L27) that says, "Hello, press the button below to manage your notification preferences." and then has a button to link back to the preferences page. Similar to how the welcome and new appointment emails are setup.

2. Update the preferences page to display a form that accepts an email and calls the new endpoint if:
    * There isn't a `token` query param in the URL
    * Or the API errors out when trying to load the user's notification preferences


If you have any better ideas for what the route should be, I'm all for it. Non restful endpoints like this are always a pain to name haha.
